{
 "title": "GRest Operator's monitoring",
 "description": "Stake Pool Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Servers State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_status{state=\"PROCOK\",proxy=\"grest_core\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "DB Size (GB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "dbsize/1024/1024/1024  ", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    { "expr": "(memused / memtotal)* 100", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "Block height (node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "nodeBlockHeight", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "Block height (dbsync)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "dbsyncBlockHeight", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "Queue Length (dbsync)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "dbsyncQueueLength", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Load" }
   ],
   "targets": [
    { "expr": "(load1m/100)", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "Tipp diff (node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "abs(nodetipref)", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "Tipp diff (dbsync)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "dbsynctipref", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    { "expr": "abs(cpuutil)", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "Uptime (node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "uptime", "legendFormat": "{{ service }}" }
   ]
  }
 ]
}