{
 "title": "Koios Monitoring",
 "description": "HAproxy backend servers",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-60m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status, proxy)"
    }
   },
   {
    "name": "instance",
    "label": "Load Balancer",
    "query": {
     "query": "label_values(haproxy_backend_status, instance)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_check_status{proxy=~\"$backend\"}, server)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Servers UP (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_status{state=\"PROCOK\",proxy=\"grest_core\",instance=~\"$instance\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Servers Down (Stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_status{state=\"PROCERR\",proxy=\"grest_core\",instance=~\"$instance\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Proxy Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "haproxy_backend_status{proxy=\"grest_core\",state=\"UP\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "New Connections Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connection_attempts_total{proxy=~\"$backend\", server=~\"$server\", proxy=\"grest_core\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "New Session Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_sessions_total{proxy=~\"$backend\",proxy=\"grest_core\" , server=~\"$server\", instance=~\"$instance\"}[360s])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Total Connections (volatile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_connection_attempts_total{proxy=~\"$backend\", server=~\"$server\",proxy=\"grest_core\", instance=~\"$instance\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_in_total{proxy=~\"$backend\", server=~\"$server\",proxy=\"grest_core\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_out_total{proxy=~\"$backend\", server=~\"$server\",proxy=\"grest_core\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  { "title": "Backend Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "HTTP Responses [2xx]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_http_responses_total{proxy=~\"$backend\", server=~\"$server\", code=~\"2xx\",proxy=\"grest_core\" , instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "HTTP Responses [4xx]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_http_responses_total{proxy=~\"$backend\", server=~\"$server\", code=~\"4xx\",proxy=\"grest_core\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "HTTP Responses [5xx]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_http_responses_total{proxy=~\"$backend\", server=~\"$server\", code=~\"5xx\",proxy=\"grest_core\"  , instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connection_errors_total{proxy=~\"$backend\", server=~\"$server\",proxy=\"grest_core\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Response Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_response_errors_total{proxy=~\"$backend\", server=~\"$server\",proxy=\"grest_core\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Check Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_check_failures_total{proxy=~\"$backend\", server=~\"$server\",proxy=\"grest_core\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ server }}"
    }
   ]
  }
 ]
}